### ISSUE TITLE
Drop-In: Exception thrown

### ISSUE THREAD

**Issue by robocup-hl-tc** [RoboCup-Humanoid-TC/GameController#35] opened 2017-05-04 16:41 UTC
_Exception in thread "main" java.lang.StackOverflowError at controller.ui.ui.HL_DropIn.dispose(Unknown Source)_

Unfortunately not easy to reproduce, but thrown at some point and then very often in a row. Doesn't seem to affect the functionality, only printed in the console.

**Comment by sheepsy90** [comment] 2017-06-25 17:02
Could not reproduce so far so will close this until it comes up again

**Closed by sheepsy90** 2017-06-25 17:02 UTC
Labels: bug
