### ISSUE TITLE
Error when executing corner kick

### ISSUE THREAD

**Issue by omichel** [RoboCup-Humanoid-TC/GameController#128] opened 2021-04-13 10:21 UTC
After sending the CORNERKICK:1 and CORNERKICK:1:EXECUTE messages from the referee, I press the "End placing" and "execute" buttons from the GameController GUI and get this error. The same error occurs also when I perform all the same operations from the GUI.
```
Exception in thread "AWT-EventQueue-0" java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at data.states.GameClock.getExtraClocks(Unknown Source)
	at controller.ui.ui.components.ClockComponent.updateExtraClocks(Unknown Source)
	at controller.ui.ui.components.ClockComponent.update(Unknown Source)
	at controller.ui.ui.AbstractUI.update(Unknown Source)
	at controller.EventHandler.update(Unknown Source)
	at controller.EventHandler.access$000(Unknown Source)
	at controller.EventHandler$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by MaikePaetzel** [comment] 2021-04-13 12:05
Duplicate of #124

**Closed by MaikePaetzel** 2021-04-13 12:05 UTC
